#!/bin/bash

NAME=$HOME/.check_crontab.sh
CRON="$HOME/.cron__sha256"
CRON_TMP=/tmp/cron.tmp # tmp sha256
CRONTAB=/etc/crontab

cat <<EOF > $NAME
#!/bin/sh
cat $CRONTAB | shasum -a 256 > $CRON_TMP
if [ -f $CRON ]; then
	diff $CRON $CRON_TMP
else
	echo "$CRON does not exist yet" #returns 0
fi
if [ \$? -ne "0" ]
then
  echo "The cron tasks were modified!"
	echo "The cron tasks were modified!" | mail -s "Cron was modified at timestamp: \`stat -c %Z $CRONTAB\`" root
fi
cat $CRONTAB | shasum -a 256 > $CRON
EOF

crontab -l > $CRON_TMP
chmod 755 $NAME \
	&& echo "0 0 * * * $NAME" >> $CRON_TMP \
	&& crontab $CRON_TMP \
	&& rm $CRON_TMP
